// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HamepageDocumentDataSlicesSlice = OptionSectionSlice | BannerSlice;

/**
 * Content for HamePage documents
 */
interface HamepageDocumentData {
  /**
   * Title field in *HamePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hamepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *HamePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hamepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HamepageDocumentDataSlicesSlice> /**
   * Meta Description field in *HamePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: hamepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HamePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hamepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *HamePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: hamepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * HamePage document from Prismic
 *
 * - **API ID**: `hamepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HamepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HamepageDocumentData>,
    "hamepage",
    Lang
  >;

/**
 * Item in *Nav Items → Items*
 */
export interface NavItemsDocumentDataItemItem {
  /**
   * Item field in *Nav Items → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_items.item[].item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item: prismic.KeyTextField;

  /**
   * Link field in *Nav Items → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_items.item[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Nav Items documents
 */
interface NavItemsDocumentData {
  /**
   * Items field in *Nav Items*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_items.item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  item: prismic.GroupField<Simplify<NavItemsDocumentDataItemItem>>;
}

/**
 * Nav Items document from Prismic
 *
 * - **API ID**: `nav_items`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavItemsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavItemsDocumentData>,
    "nav_items",
    Lang
  >;

/**
 * Item in *Popular Brands → Brand*
 */
export interface PopularBrandsDocumentDataBrandItem {
  /**
   * Title field in *Popular Brands → Brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_brands.brand[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Logo field in *Popular Brands → Brand*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_brands.brand[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Content for Popular Brands documents
 */
interface PopularBrandsDocumentData {
  /**
   * Brand field in *Popular Brands*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_brands.brand[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  brand: prismic.GroupField<Simplify<PopularBrandsDocumentDataBrandItem>>;
}

/**
 * Popular Brands document from Prismic
 *
 * - **API ID**: `popular_brands`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PopularBrandsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PopularBrandsDocumentData>,
    "popular_brands",
    Lang
  >;

/**
 * Content for Single Data documents
 */
interface SingleDataDocumentData {
  /**
   * Logo field in *Single Data*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: single_data.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  logo: prismic.EmbedField;
}

/**
 * Single Data document from Prismic
 *
 * - **API ID**: `single_data`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SingleDataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SingleDataDocumentData>,
    "single_data",
    Lang
  >;

export type AllDocumentTypes =
  | HamepageDocument
  | NavItemsDocument
  | PopularBrandsDocument
  | SingleDataDocument;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Image field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Talk About field in *Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.talk_about
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  talk_about: prismic.KeyTextField;

  /**
   * Title field in *Banner → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *Banner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceReversePrimary {
  /**
   * Image field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Banner → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;

  /**
   * Button field in *Banner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;
}

/**
 * Reverse variation for Banner Slice
 *
 * - **API ID**: `reverse`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceReverse = prismic.SharedSliceVariation<
  "reverse",
  Simplify<BannerSliceReversePrimary>,
  never
>;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceOptionListPrimary {
  /**
   * Image field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Banner → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Banner → Items*
 */
export interface BannerSliceOptionListItem {
  /**
   * Option field in *Banner → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  option: prismic.KeyTextField;
}

/**
 * Option List variation for Banner Slice
 *
 * - **API ID**: `optionList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceOptionList = prismic.SharedSliceVariation<
  "optionList",
  Simplify<BannerSliceOptionListPrimary>,
  Simplify<BannerSliceOptionListItem>
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation =
  | BannerSliceDefault
  | BannerSliceReverse
  | BannerSliceOptionList;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *OptionSection → Primary*
 */
export interface OptionSectionSliceDefaultPrimary {
  /**
   * Title field in *OptionSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: option_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *OptionSection → Items*
 */
export interface OptionSectionSliceDefaultItem {
  /**
   * Title field in *OptionSection → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: option_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *OptionSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: option_section.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for OptionSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OptionSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OptionSectionSliceDefaultPrimary>,
  Simplify<OptionSectionSliceDefaultItem>
>;

/**
 * Slice variation for *OptionSection*
 */
type OptionSectionSliceVariation = OptionSectionSliceDefault;

/**
 * OptionSection Shared Slice
 *
 * - **API ID**: `option_section`
 * - **Description**: OptionSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OptionSectionSlice = prismic.SharedSlice<
  "option_section",
  OptionSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HamepageDocument,
      HamepageDocumentData,
      HamepageDocumentDataSlicesSlice,
      NavItemsDocument,
      NavItemsDocumentData,
      NavItemsDocumentDataItemItem,
      PopularBrandsDocument,
      PopularBrandsDocumentData,
      PopularBrandsDocumentDataBrandItem,
      SingleDataDocument,
      SingleDataDocumentData,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceReversePrimary,
      BannerSliceOptionListPrimary,
      BannerSliceOptionListItem,
      BannerSliceVariation,
      BannerSliceDefault,
      BannerSliceReverse,
      BannerSliceOptionList,
      OptionSectionSlice,
      OptionSectionSliceDefaultPrimary,
      OptionSectionSliceDefaultItem,
      OptionSectionSliceVariation,
      OptionSectionSliceDefault,
    };
  }
}
