import type { Metadata } from 'next'
import {  Vazirmatn } from 'next/font/google'
import './globals.css'
import { PrismicPreview } from '@prismicio/next'
import { repositoryName } from '@/prismicio'

const vazirmatn = Vazirmatn({ subsets: ['latin'] , variable: "--font-vazirmatn", display: "swap"})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body className={vazirmatn.className}>
        {children}
        <PrismicPreview repositoryName={repositoryName} />
        </body>
    </html>
  )
}
