import type { Metadata } from 'next'
import { Vazirmatn } from 'next/font/google'
import './globals.css'
import { createClient } from '@/prismicio'
import Navigation from '@/components/navigation'
import Footer from '@/components/Footer'

const vazirmatn = Vazirmatn({ subsets: ['latin'], variable: "--font-vazirmatn", display: "swap" })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const client = createClient()
    const { data: navigationData } = await client.getSingle("nav_items")
    const {data: footerData} = await client.getSingle("footer")


    return (
        <html lang="en" dir='rtl'>
            <body className={`${vazirmatn.className} bg-gray-50`}>
                <Navigation items={navigationData.item} />ّ
                {children}
                <Footer listItem={footerData.slices}/>
            </body>
        </html>
    )
}
