// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  brands_list: dynamic(() => import("./BrandsList")),
  dis_clouser: dynamic(() => import("./DisClouser")),
  footer_section: dynamic(() => import("./FooterSection")),
  option_section: dynamic(() => import("./OptionSection")),
  search_box: dynamic(() => import("./SearchBox")),
};
